### ISSUE TITLE
Update link

### ISSUE THREAD

**Issue by jerolomb** [monarc-project/migration_tool#1]
Update the packages.json and composer.json to use the right repositories.

**Comment by cedricbonhomme** [comment]
Is the file _archive/master.zip_ missing from the repository?

https://github.com/monarc-project/migration_tool/blob/866712bf80b74e3a0cd74a048f90b97f150f5b65/packages.json#L17

**Comment by cedricbonhomme** [comment]
oh no sorry, I think that its' just the repository export. Not a part of the repo...
